### PR TITLE
Externalize const_generators for shared library

### PR DESCRIPTION
**Pull request by FrankC01**
Updated secp256k1_generator_const_g and secp256k1_generator_const_h declarations

### CODE REVIEW

**Comment by apoelstra** [comment]
Can you PR this against upstream ElementsProject/secp256k1-zkp ?

**Comment by FrankC01** [comment]
In addition to this one?

**Comment by apoelstra** [comment]
and close this one, I guess

**Comment by FrankC01** [comment]
I'm confused

This one addresses both generators in `-mw`. The main branch of `-zkp` only has one generator in rangeproofs.h. 

By closing this one, using -mw (bulletproofs) would still have the problem without the merge no?

**Comment by apoelstra** [comment]
The -mw fork is not maintained, it is just my personal copy of -zkp. To the extent its main branch differs from -zkp, it constitutes completely unreviewed code.

**Comment by FrankC01** [comment]
Closing as per request.

**Comment by apoelstra** [comment]
I've updated https://github.com/ElementsProject/secp256k1-zkp/pull/23 to fix this issue.

**Pull request closed without merging**
